flannel_bin_dir: "/opt/k8s/flannel"
etcd_listen_port: 2380
etcd_client_port: 2379
flannel_version: "v0.10.0"
flannel_cni_spec_version: "0.3.1"
flannel_etcd_prefix: "/coreos.com/network"
flannel_ip_range: "10.5.0.0/16"
flannel_backend_type: vxlan
k8s_cni_conf_dir: "/etc/cni/net.d"
flannel_cni_interface: "wlp4s0"
flannel_settings:
  "etcd-endpoints": http://{{ hostvars['kube00']['ansible_host'] }}:2379
  "etcd-prefix": "{{ flannel_etcd_prefix }}"
  "iface": "{{ ansible_default_ipv4.address }}"
  "public-ip": "{{ ansible_default_ipv4.address }}"
  "ip-masq": "true"
  "healthz-ip": "0.0.0.0"
  "healthz-port": "0" # 0 = disable


{ "Network": "10.6.0.0/16", "Backend": {"Type": "vxlan"}}
'{ "Network": "10.5.0.0/16","Backend" : {"Type": "vxlan"}}'