- name: Create k8s certficate directory
  file: 
    path: "{{ ca-cert-path }}"
    owner: "{{ dirowner }}"
    group: "{{ dirowner }}"
    mode: 0755 
    state: directory

- name: "Generate Certs for k8s server || CA setup "
  shell: 'openssl genrsa -out {{ ca-cert-path }}/ca-key.pem 2048'
