- name: "Create k8s certficate directory || CA setup. "
  file: 
    path: "{{ ca.certpath }}"
    owner: "{{ ca.dirowner }}"
    group: "{{ ca.dirowner }}"
    mode: 0755 
    state: directory

- name: "Create k8s csr directory || CA setup. "
  file: 
    path: "{{ ca.reqpath }}"
    owner: "{{ ca.dirowner }}"
    group: "{{ ca.dirowner }}"
    mode: 0755 
    state: directory

- name: "Generate key for k8s api || CA setup. "
  shell: 'openssl genrsa -out {{ ca.certpath }}/{{ ca.keyfile }} 2048'
  args:
    creates: "{{ ca.certpath }}/{{ ca.keyfile }}"

- name: "Generate self signed certs for k8s api || CA setup. "
  shell: 'openssl req -x509 -new -key {{ ca.certpath }}/{{ ca.keyfile }} -out {{ ca.certpath }}/{{ ca.certfile }} -subj "/O=kubernetes/CN=kubernetes" -config {{ role_path }}/files/server-openssl.cnf' 
  args: 
    creates: "{{ ca.certpath }}/{{ ca.certfile }}"

- name: "Generate key for k8s server || CA setup. "
  shell: 'openssl genrsa -out {{ server.certpath }}/{{ server.keyfile }} 2048'
  args:
    creates: "{{ server.certpath }}/{{ server.keyfile }}"

- name: "Generate csr for k8s server || CA setup. "
  shell: 'openssl req -new -key {{ server.certpath }}/{{ server.keyfile }} -subj "/CN={{ server.ip }}"  -out {{ server.reqpath }}/server.csr -config {{ role_path }}/files/server-openssl.cnf' 
  args: 
    creates: "{{ server.certpath }}/{{ server.certfile }}"


- name: "Generate certs for k8s server || CA setup. "
  shell: 'openssl x509 -req -in {{ server.reqpath }}/server.csr -CA {{ ca.certpath }}/{{ ca.certfile }} -CAkey {{ ca.certpath }}/{{ ca.keyfile }} -CAcreateserial -out {{ server.certpath }}/{{ server.certfile }} -days 10000 -extensions v3_req -extfile {{ role_path }}/files/server-openssl.cnf' 
  args: 
    creates: "{{ server.certpath }}/{{ server.certfile }}"

- name: "Generate key for server admin || CA setup. "
  shell: 'openssl genrsa -out {{ server.certpath }}/{{ server.keyfile }} 2048'
  args:
    creates: "{{ admin.certpath }}/{{ admin.keyfile }}"

- name: "Generate csr for server admin || CA setup. "
  shell: 'openssl req -new -key {{ admin.certpath }}/{{ admin.keyfile }} -subj "/CN=admin/O=system:masters"  -out {{ admin.reqpath }}/admin.csr -config {{ role_path }}/files/server-openssl.cnf' 
  args: 
    creates: "{{ admin.certpath }}/{{ admin.certfile }}"

- name: "Generate certs for server admin || CA setup. "
  shell: 'openssl x509 -req -in {{ admin.reqpath }}/admin.csr -CA {{ ca.certpath }}/{{ ca.certfile }} -CAkey {{ ca.certpath }}/{{ ca.keyfile }} -CAcreateserial -out {{ admin.certpath }}/{{ admin.certfile }} -days 10000 -extensions v3_req -extfile {{ role_path }}/files/server-openssl.cnf' 
  args: 
    creates: "{{ admin.certpath }}/{{ admin.certfile }}"