- name: Create k8s certficate directory
  file: 
    path: "{{ ca.certpath }}"
    owner: "{{ ca.dirowner }}"
    group: "{{ ca.dirowner }}"
    mode: 0755 
    state: directory

- name: "Generate Certs for k8s server || CA setup "
  shell: 'openssl genrsa -out {{ ca.certpath }}/ca-key.pem 2048'
