- name: Setting up k8s 
  hosts: k8s_masters

  roles:
    - role: setup-ca
      tags: certs
    - { role: setup-ca,  tags: certs }
    - role: create-authfiles
      tags: authfiles
    - { role: create-authfiles,  tags: authfiles }
