- name: Setting up k8s 
  hosts: k8s_masters

  roles:
    - role: gen-ssl-conf
      tags: ssl
    - { role: gen-ssl-conf,  tags: ssl }
    - role: setup-ca
      tags: certs
    - { role: setup-ca,  tags: certs }
    - role: dep-packages
      tags: packages
    - { role: dep-packages,  tags: packages }
    - role: create-authfiles
      tags: authfiles
    - { role: create-authfiles,  tags: authfiles }
    - role: k8s-etcd-deploy
      tags: etcd-deploy
    - { role: k8s-etcd-deploy,  tags: etcd-deploy }
    - role: k8s-master-deploy
      tags: apiserver-deploy
    - { role: k8s-master-deploy,  tags: master-deploy }
    - role: k8s-node-deploy
      tags: node-deploy
    - { role: k8s-node-deploy,  tags: node-deploy }
