- name: Setting up k8s 
  hosts: k8s_masters,k8s_nodes

  roles:
    - role: gen-ssl-conf
      tags: gen-conf
    - { role: gen-ssl-conf,  tags: gen-conf }
    - role: setup-ca
      tags: gen-certs
    - { role: setup-ca,  tags: gen-certs }
    - role: dep-packages
      tags: packages
    - { role: dep-packages,  tags: packages }
    - role: create-authfiles
      tags: authfiles
    - { role: create-authfiles,  tags: authfiles }
    - role: k8s-etcd-deploy
      tags: etcd-deploy
    - { role: k8s-etcd-deploy,  tags: etcd-deploy }
    - role: k8s-master-deploy
      tags: apiserver-deploy
    - { role: k8s-master-deploy,  tags: master-deploy }
    - role: k8s-node-deploy
      tags: node-deploy
    - { role: k8s-node-deploy,  tags: node-deploy }
    - role: flannel-setup
      tags: flannel-deploy
    - { role: flannel-setup,  tags: flannel-deploy }
