- name: Setting up k8s 
  hosts: k8s_masters

  roles:
    - role: gen-ssl-conf
      tags: ssl
    - { role: gen-ssl-conf,  tags: ssl }
    - role: setup-ca
      tags: certs
    - { role: setup-ca,  tags: certs }
    - role: dep-packages
      tags: packages
    - { role: dep-packages,  tags: packages }
    - role: create-authfiles
      tags: authfiles
    - { role: create-authfiles,  tags: authfiles }
    - role: dep-packages
      tags: etcd-dependency
    - { role: dep-packages,  tags: etcd-dependency }
