- name: "Create etcd data directory || etcd deploy."
  file: 
    path: "/opt/k8s/etcd/data"
    owner: "root"
    group: "root"
    mode: 0750 
    state: directory
    recurse: yes

- name: "Create etcd data directory || etcd deploy."
  file: 
    path: "/opt/k8s/etcd/bin"
    owner: "root"
    group: "root"
    mode: 0750 
    state: directory
    recurse: yes

- name: "Download etcd binaries || k8s node deploy."
  unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v3.4.14/etcd-v3.4.14-linux-amd64.tar.gz
    dest: "/opt/k8s/etcd/bin"
    remote_src: yes
    owner: root
    group: root
    mode: 0750 
    extra_opts: [--strip-components=1]
    exclude:
      - Documentation
      - README-etcdctl.md
      - README.md
      - READMEv2-etcdctl.md


- name: Generating systemd for etcd daemon || etcd deploy.
  vars:
    servers: "{{ groups['k8s_masters'] }}"
    etcd:
      version: v3.0.0
      token: my-etcd-token
      clusterstate: new
      datapath: '/opt/k8s/etcd/data'
      image: 'quay.io/coreos/etcd'
  template:
    src: "{{ role_path }}/files/etcd-systemd.j2"
    dest: "/etc/systemd/system/etcd.service"
    owner: root
    group: root

  with_items: servers

- name: Reloading systemd || etcd deploy.
  systemd:
    daemon_reload: yes