---
- name: Gather instance facts
  setup:

- name: Create Flannel config directory
  file:
    path: "{{ flannel_bin_dir }}"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create CNI config directory
  file:
    path: "{{ k8s_cni_conf_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install flanneld CNI config
  template:
    src: "{{ role_path }}/files/flannel-conf.j2"
    dest: "{{ k8s_cni_conf_dir }}/10-flannel.conflist"
    mode: 0600

- name: Setup flannel network configuration in etcd if needed
  shell: |
     ETCDCTL_API=2 /opt/k8s/etcd/bin/etcdctl \
      --endpoints="http://{{ hostvars['kube00']['ansible_host'] }}:{{ etcd_client_port }}" \
      set /coreos.com/network/config '{"Network": "{{ flannel_ip_range }}","Backend": {"Type": "{{ flannel_backend_type }}"}}'
  run_once: true

- name: Downloading official flanneld binary
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flanneld-amd64"
    dest: "{{ flannel_bin_dir }}/flanneld"
    mode: 0750

- name: Install systemd service for flanneld
  template:
    src: "{{ role_path }}/files//flannel_systemd.j2"
    dest: /etc/systemd/system/flanneld.service
    owner: root
    group: root
    mode: 0644

