- name: "Download k8s node binaries || k8s node deploy."
  unarchive:
    src: https://dl.k8s.io/v1.19.0/kubernetes-node-linux-amd64.tar.gz
    dest: /opt/k8s/
    remote_src: yes
    owner: root
    group: root
    mode: 0750 
    extra_opts: [--strip-components=1]
    exclude:
      - LICENSES
      - kubernetes-src.tar.gz

- name: Generating systemd for kubelet daemon || master deploy.
  template:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
  with_items:
    - { src: '{{ role_path }}/files/kubelet-systemd.j2', dest: '/etc/systemd/system/kubelet.service' }
    - { src: '{{ role_path }}/files/kubeletConfig.j2', dest: '/opt/k8s/node/conf/kubelet-config.yaml' }

- name: Reloading systemd || master deploy.
  systemd:
    daemon_reload: yes