- name: "Download k8s node binaries || k8s node deploy."
  unarchive:
    src: https://dl.k8s.io/v1.19.0/kubernetes-node-linux-amd64.tar.gz
    dest: /opt/k8s/
    remote_src: yes
    owner: root
    group: root
    mode: 0750 
    extra_opts: [--strip-components=1]
    exclude:
      - LICENSES
      - kubernetes-src.tar.gz

- name: "Create node conf directory || k8s node deploy."
  file: 
    path: "/opt/k8s/node/conf"
    owner: "root"
    group: "root"
    mode: 0750 
    state: directory
    recurse: yes

- name: Generating systemd for kubelet daemon || k8s node deploy.
  template: # src={{item.src}} dest={{item.dest}}
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    force: yes
  with_items:
    - { src: "files/kubelet-systemd.j2", dest: "/etc/systemd/system/kubelet.service" }
    - { src: "files/kubeletConfig.j2", dest: "/opt/k8s/node/conf/kubelet-config.yaml" }

- name: Reloading systemd || k8s node deploy.
  systemd:
    daemon_reload: yes