- name: "Create k8s certficate directory || CA setup. "
  vars:
    sannames: "{{ groups['k8s_nodes'] }}"
  file: 
    path: "{{ ca.certpath }}"
    owner: "{{ ca.dirowner }}"
    group: "{{ ca.dirowner }}"
    mode: 0755 
    state: directory