- name: Generating ssl conf file from inventory
  template:
    src: /role_path/files/ssl-template.j2
    dest: /inventory_dir/setup-ca/files/server-ssl.cnf
    owner: root
    group: root
    mode: '0640'
- name: Adding SANs from inventory 
  lineinfile:
    dest: /inventory_dir/setup-ca/files/server-ssl.cnf
    # regexp: "{{ item.regexp }}"
    line: "{{ item }}"
  with_items: "{{ groups['k8s_nodes','k8s_masters'] }}"