- name: Generating SSL config file from node list || Generating cert config.
  vars:
    servers: "{{ groups['k8s_nodes'] }}"
  template:
    src: "/{{ lookup('env', 'PWD') }}/roles/gen-ssl-conf/files/ssl-template.j2"
    dest: "/{{ lookup('env', 'PWD') }}/roles/setup-ca/files/server-ssl.cnf"
    owner: root
    group: root

  with_items: servers
