# - name: Find out playbook's path
#   shell: pwd
#   register: playbook_path_output
# - debug: var=playbook_path_output.stdout

- name: Generating ssl conf file from inventory
  template:
    src: /{{ PWD }}/gen-ssl-conf/files/ssl-template.j2
    dest: /inventory_dir/setup-ca/files/server-ssl.cnf
    owner: root
    group: root
    mode: '0640'

- name: Adding SANs from inventory 
  lineinfile:
    dest: /{{ PWD }}/setup-ca/files/server-ssl.cnf
    # regexp: "{{ item.regexp }}"
    line: "{{ item }}"
  with_items: "{{ groups['k8s_nodes','k8s_masters'] }}"